@url = http://localhost:8080/finding-wildlife/sighting
@JWT_TOKEN = eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJmaW5kaW5nLXdpbGRsaWZlIiwic3ViIjoibWFyeWRvZUBob3RtYWlsLmNvbSIsImF1dGhvcml0aWVzIjoiUk9MRV9VU0VSIiwiYXBwVXNlcklkIjoyLCJleHAiOjE2NjUwMTI5ODN9.0i_6KhVEr9Pygmno1APcA1o_v3DSgn0xaz0W01CvDe4

POST http://localhost:8080/create_account HTTP/1.1
Content-Type: application/json

{
    "username": "krmorales",
    "password": "P@ssw0rd!"
}

###

POST http://localhost:8080/authenticate HTTP/1.1
Content-Type: application/json

{
     "username": "marydoe@hotmail.com",
     "password": "P@ssw0rd!"
}

###

GET {{url}}/date/2021-01-01/2021-12-30/3 HTTP/1.1

###

GET {{url}}/national-park/Yellowstone National Park HTTP/1.1

###

GET {{url}}/White-tailed deer HTTP/1.1

###

GET {{url}}/sightingId/2 HTTP/1.1

###

GET {{url}}/userId/2 HTTP/1.1
Authorization: Bearer {{JWT_TOKEN}}

###

POST {{url}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{JWT_TOKEN}}

{
  "date": "2022-09-27",
  "time": "05:45",
  "comments": "Test",
  "latitude": 100.25,
  "longitude": -56.23,
  "parkId": 1,
  "organismId": 1,
  "appUserId": 2
}

###

PUT {{url}}/2 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{JWT_TOKEN}}

{
  "sightingId": 2,
  "date": "2022-09-27",
  "time": "05:45",
  "comments": "Test",
  "latitude": 100.25,
  "longitude": -56.25,
  "parkId": 1,
  "organismId": 2,
  "appUserId": 2
}


###

DELETE {{url}}/2/2 HTTP/1.1
Authorization: Bearer {{JWT_TOKEN}}
